-- Add display_id column to profiles
-- This ID will be auto-incrementing starting from 1, used for public URLs

-- 1. Add the column (nullable first to allow backfill)
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS display_id BIGINT;

-- 2. Backfill existing users
-- We order by created_at to preserve seniority
WITH numbered_profiles AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) as rn
  FROM profiles
)
UPDATE profiles
SET display_id = numbered_profiles.rn
FROM numbered_profiles
WHERE profiles.id = numbered_profiles.id;

-- 3. Make it required and unique
ALTER TABLE profiles 
ALTER COLUMN display_id SET NOT NULL;

ALTER TABLE profiles 
ADD CONSTRAINT profiles_display_id_key UNIQUE (display_id);

-- 4. Set it to auto-increment for future inserts
-- We need to find the max current ID to set the sequence start correctly
DO $$
DECLARE
  max_id BIGINT;
BEGIN
  SELECT COALESCE(MAX(display_id), 0) + 1 INTO max_id FROM profiles;
  
  -- Alter the column to be an identity column starting from max_id
  EXECUTE format('ALTER TABLE profiles ALTER COLUMN display_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)', max_id);
END $$;

-- 5. Add Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_profiles_display_id ON profiles(display_id);
